"""empty message

Revision ID: 976beffd1f0a
Revises: 27ed765c2b84
Create Date: 2024-09-21 10:54:50.909407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976beffd1f0a'
down_revision = '27ed765c2b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_auth_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_auth_username'), ['username'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_userid')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_user_userid', ['userid'], unique=False)

    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_auth_username'))
        batch_op.drop_index(batch_op.f('ix_user_auth_email'))

    op.drop_table('user_auth')
    # ### end Alembic commands ###
